### ISSUE TITLE
Update setup.py with hgvs-eval package info, name, description

### ISSUE THREAD

**Issue by davecap** [biocommons/hgvs-eval#16]
I noticed that setup.py may not be up to date. Maybe @reece can update it? Not sure if there is some kind of biocommons package naming scheme you want to go with.

**Comment by davecap** [comment]
The version check in `__init__.py` seems to depend on the package name being the same as `__name__`, which I guess is `hgvseval`.

**Comment by reece** [comment]
I'm not sure what the symptom was there,  but I updated the README and verified that I could bring the server up and invoke tests (which happen to fail at the moment) as described there.

**Comment by davecap** [comment]
Oh I just assumed the package name `biocommons.pkg` may not be right, maybe it's fine though.
